from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle

def create_test_pdf(filename):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(100, 750, "Test PDF Document")

    # Text
    c.setFont("Helvetica", 12)
    c.drawString(100, 700, "This is a test document to verify PDF to DOCX conversion.")
    c.drawString(100, 680, "It contains text, a table, and some formatting.")

    # Table
    data = [['Header 1', 'Header 2', 'Header 3'],
            ['Row 1 Col 1', 'Row 1 Col 2', 'Row 1 Col 3'],
            ['Row 2 Col 1', 'Row 2 Col 2', 'Row 2 Col 3']]
    
    t = Table(data)
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                           ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                           ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                           ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                           ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                           ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                           ('GRID', (0, 0), (-1, -1), 1, colors.black)]))
    
    t.wrapOn(c, width, height)
    t.drawOn(c, 100, 500)

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(100, 50, "Generated by ReportLab")

    c.save()

if __name__ == "__main__":
    create_test_pdf("test_layout.pdf")
    print("PDF created: test_layout.pdf")
